language: ruby

rvm:
  - 2.7

cache:
  directories:
  - $HOME/nats-server

before_install:
  - bash ./scripts/install_gnatsd.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

sudo: required
dist: xenial
bundler_args: --without server
